name: Generate PDF
on: [push]
jobs:
    compile:
        runs-on: ubuntu-18.04
        steps:
            - name: Set up Git repository
              uses: actions/checkout@v2
            - name: Compile LaTeX document
              uses: xu-cheng/latex-action@v2
              with:
                root_file: main.tex
            - name: 'Upload Artifact'
              uses: actions/upload-artifact@v2
              with:
                name: dokumentationpdf
                path: main.pdf
            - run: mkdir public
            - run: mv ./main.pdf ./public/main.pdf
            - name: Deploy
              uses: peaceiris/actions-gh-pages@v3
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                publish_dir: ./public

