name: Generate PDF
on: [push]
jobs:
    compile:
        runs-on: ubuntu-latest
        steps:
            - name: Set up Git repository
              uses: actions/checkout@
            - run: sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys D6BC243565B2087BC3F897C9277A7293F59E4889
            - run: echo "deb http://miktex.org/download/ubuntu bionic universe" | sudo tee /etc/apt/sources.list.d/miktex.list
            - run: sudo apt-get update
            - run: sudo apt-get install miktex
            - run: echo "Start compiling"
            - run: texify -p main.tex
            - run: echo "Finished compiling"
            - name: 'Upload Artifact'
              uses: actions/upload-artifact@v2
              with:
                name: dokumentationpdf
                path: main.pdf
                retention-days: 5
